# Warning: Do not unify this file with others. Keep tool definitions localized.
[tools]
bun = "1.3.8"
go = "1.26.0"
"go:golang.org/x/tools/gopls" = "0.21.0"
golangci-lint = "1.64.8"
trunk = "1.3.4"

[tasks.lint]
run = "trunk check"

[tasks.fmt]
run = "trunk fmt"

[tasks.codegen]
depends = ["fmt"]

[tasks.ci]
depends = ["lint"]
