# Warning: Do not unify this file with others. Keep tool definitions localized.
[tools]
go = "1.26.0"
"go:golang.org/x/tools/gopls" = "0.21.0"

[tasks.lint]
run = "go run ./cmd/workspaced codebase lint"

[tasks.fmt]
run = "go run ./cmd/workspaced codebase format"

[tasks.codegen]
depends = ["fmt"]

[tasks.ci]
depends = ["lint"]
